mpi:
  - mpich
  - openmpi

# FIXME: seems to be problems with clang 16
# causing weird link errors
c_compiler_version:
  - 15  # [osx]
cxx_compiler_version:
  - 15  # [osx]

pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  eigen:
    max_pin: x.x
  parmetis:
    max_pin: x.x
  # pybind11 generation breaks on patch releases
  # at least between 2.2.3 and 2.2.4
  pybind11:
    max_pin: x.x.x
