{% set version = "2017.2.0" %}
{% set petsc_version = '3.8.*' %}
{% set swig_version = '3.0.12' %}
{% set mpi = "mpich" %}
{% set mpi_version = '3.2.*' %}

package:
  name: fenics
  version: {{version}}

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-{{version}}.post0.tar.gz
  sha256: d3c40cd8c1c882f517999c25ea4220adcd01dbb1d829406fce99b1fc40184c82

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - cmake >=3.9
    - pkg-config
    - cmake >=3.9
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # Make sure libgcc 5.* is not used at build time
    - boost
    - eigen 3.3.*
    - ptscotch 6.0.4
    - zlib
    - {{mpi}} {{mpi_version}}
    - openblas
    - petsc {{petsc_version}}
    - petsc4py {{petsc_version}}
    - slepc {{petsc_version}}
    - slepc4py {{petsc_version}}
    - swig {{swig_version}}
    - numpy        *openblas*
    - ply
    - six
    - subprocess32  # [py2k]
    - sympy
    - hdf5

  run:
    - python
    - setuptools
    - boost
    - eigen 3.3.*
    - {{mpi}} {{mpi_version}}
    - openblas
    - petsc {{petsc_version}}
    - petsc4py {{petsc_version}}
    - slepc {{petsc_version}}
    - slepc4py {{petsc_version}}
    - ptscotch 6.0.4
    - zlib
    - ply
    - swig {{swig_version}}
    - {{ pin_compatible('numpy') }}  *openblas*
    - six
    - subprocess32  # [py2k]
    - sympy
    - hdf5

test:
  source_files:
    - test

  requires:
    - nose
    - pytest
    - git
    - decorator

  imports:
    - dijitso
    - instant
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms
    - FIAT
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - dolfin

  commands:
    - instant-clean
    - instant-showcache

    - ufl-version
    - ufl2py --help

    - ffc --help

about:
  home: http://www.fenicsproject.org
  license: LGPL 3.0
  license_file: COPYING.LESSER
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (<http://fenicsproject.org>). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: http://fenics.readthedocs.io/
  dev_url: https://bitbucket.org/fenics-project/

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
