{% set version = "2016.2.dev" %}
package:
  name: fenics
  version: {{version}}

source:
  git_url: https://bitbucket.org/fenics-project/dolfin.git
  git_tag: master

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - pip
    - gcc  # [linux]
    - boost
    - cmake
    - eigen
    - pkg-config
    - toolchain
    - zlib
    - swig >=3
    - numpy
    - ply
    - six
    - sympy
    - subprocess32  # [not py3k]

  run:
    - python
    - boost
    - cmake
    - eigen
    - gcc  # [linux]
    - pkg-config
    - zlib
    - ply
    - swig >=3
    - numpy
    - six
    - sympy
    - subprocess32 # [not py3k]

test:

  requires:
    - nose
    - pytest
    - git

  files:
    - test_dolfin.py

  imports:
    - dijitso
    - instant
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms
    - FIAT
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - ffc.tensor
    - dolfin
  
  commands:
    - instant-clean
    - instant-showcache

    - ufl-version
    - ufl2py --help

    - ffc --help

about:
  home: http://www.fenicsproject.org
  license: LGPL 3.0
  license_file: COPYING.LESSER
  summary: FEniCS is a collection of free software for automated, efficient solution of differential equations

extra:
  recipe-maintainers:
    - garth-wells
    - mikaem
    - minrk
