travis:
  secure:
    BINSTAR_TOKEN: UM7Mm4KTgjWlqN1PbUDVdOhGlGJGM3qSHfR1MUSjI+eqXXG1HUYbboTok7F/JTE3VUN53HiwBNJXVP2XvE/kCXJGYI13biWkx4+umlmYmq5qZwDMDD7RwNKhrl2vYO9FdcV3F/q5aWBn0bDkKc4XZVxIixkcrhUws383Bv4gXh/yiYi0lnTFCzvfCpjl4YCO4eGwXPGPPubtoLi/sbDyz2fNY/jaylIPzfM8mWLhQ9jvC5qVJERtb3iNJl8/CFkVwaKRecUU38LCRowX9pBmYA1mTvCuAqo+BhEJRMV7H62HdUtNLdj1Z/rlIc6etX92dB2+ISUVxE8kNPWrzsNpGR1tW6hVkwkXVcCpLO+wNDhboafGQNgB/OYWULZHOxJgGVmsdnPdCBB9mUZyj+DF0YJi9IenU+ocKKZSmq4AaqwMIgtfstaykn3ae0s6Xls6KNyklH/nJtGEn0tmain9QM2SBsRFVO2dCCJ9KF3C9cEWPiEh7gEe5gYATTkrMpOhseK3ZkZBh3efodgXpMnbKMILv/ymNfC2+CSQtN0Audc7SdvEiXKwI8sMwY0UsUCCxbVntqX45dv2ZsJHO7mHC8Y9TT6UIm1Swpkjle97Ap108P3HHnFs+6szvtLbUvenAL2gzJ9dItHBZJPyJRaYCBWyEhQuR62VqgekpfOdKgE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
